package ant_art.config;

import java.awt.*;

/**
 * Created By: Prashant Chaubey
 * Created On: 29-04-2020 00:17
 * Purpose: Configuration of the project
 **/
public final class Configuration {
    private Configuration() {
    }

    /**
     * Constants used to create OIL painting.
     */
    public final class OilPainting {
        private OilPainting() {
        }

        public static final int RADIUS = 5;
        public static final int INTENSITY_LEVEL = 24;
    }

    /**
     * Constants for default directory
     */
    public final class Directories {
        private Directories() {
        }

        public static final String PALLETS = "pallets";
        public static final String INPUT = "inputs";
        public static final String OUTPUT = "outputs";
    }

    /**
     * Configuration for GUI
     */
    public final class GUI {
        private GUI() {
        }

        //GUI update rate per second
        public static final int FPS = 60;
        //Time period of the simulation in seconds
        public static final int DURATION = 30;
        //Interval at which have to take a image snapshot
        public static final int SAMPLE_INTERVAL = 5;
        public static final int UPDATE_ACCUMULATION_THRESHOLD = 5;
    }

    /**
     * Configuration for outputs generated by the system
     */
    public final class Outputs {
        private Outputs() {
        }

        public static final String IMG_FORMAT = "jpg";
    }

    /**
     * Configuration for colors in the ant area.
     * todo find why needed static
     */
    public static final class Colors {
        private Colors() {
        }

        public static final Color DEFAULT = Color.black;
        public static final Color FOOD = Color.RED;
        public static final Color NEST = Color.GREEN;
    }

    //This parameter decides the probability of ant actions. A value of 5 means that out of 5 chances ant will do a
    //thing. A probability of 1/5 = 0.2.
    public static final int ANT_SELECTION_SEED = 5;
    //The maximum food pheromone allowed on a cell
    public static final float MAX_FOOD_PHEROMONE = 50;
    //The maximum home pheromone allowed on a cell
    public static final float MAX_HOME_PHEROMONE = 50;
    //The minimum ratio of the cells which needed to mark it as a type.
    public static final float TYPE_IDENTIFICATION_THRESHOLD = 0.5f;
    //How much food that can be picked from a cell at a time.
    public static final int FOOD_PICKUP_QUANTITY = 1;
    // The color of the cell depends upon the food pheromone present on it. This multiplier will give push for low
    //pheromone levels
    public static final float INTENSITY_AMPLIFIER = 25;
    public static final int NEST_AREA_SIZE = 5;
    public static final int FOOD_AREA_SIZE = 1;
    public static final int CELL_SIZE = 4;
    public static final int MAX_ANTS = 100;
    public static final int FOOD_CELLS_TO_SPAWN = 20;
    public static final int NEST_CELLS_TO_SPAWN = 1;
    public static final int DEFAULT_FOOD_IN_CELL = 5;
    public static final float PHEROMONE_DECAY_RATE = 0.01f;
    public static final float MINIMUM_PHEROMONE_THRESHOLD = 0.01f;
    public static final float PHEROMONE_GAIN = 1;
    public static final int ANT_FOOD_CAPACITY = 100;

    public static final int COLOR_SIMILARITY_THRESHOLD = 50;
    public static final int DEFAULT_TARGET_COLOR_COUNT = 5;
    //520 works best with an FPS of 60 so change accordingly. If increasing the FPS reduce the size and vice-versa.
    public static final int MAXIMUM_IMAGE_SIZE = 520;
    public static final int MAXIMUM_RESCALING_DEPTH = 3;
    public static final float COLOR_FILTERING_HIGHER_LIMIT = 0.5f;
    public static final float COLOR_FILTERING_LOWER_LIMIT = 0.05f;

    public static final int OUTPUT_GIF_DELAY = 250;
    public static final boolean OUTPUT_GIF_LOOPING = true;
}
